require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MouvementRecurrentsController do

  # This should return the minimal set of attributes required to create a valid
  # MouvementRecurrent. As you add validations to MouvementRecurrent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MouvementRecurrentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mouvement_recurrents as @mouvement_recurrents" do
      mouvement_recurrent = MouvementRecurrent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mouvement_recurrents).should eq([mouvement_recurrent])
    end
  end

  describe "GET show" do
    it "assigns the requested mouvement_recurrent as @mouvement_recurrent" do
      mouvement_recurrent = MouvementRecurrent.create! valid_attributes
      get :show, {:id => mouvement_recurrent.to_param}, valid_session
      assigns(:mouvement_recurrent).should eq(mouvement_recurrent)
    end
  end

  describe "GET new" do
    it "assigns a new mouvement_recurrent as @mouvement_recurrent" do
      get :new, {}, valid_session
      assigns(:mouvement_recurrent).should be_a_new(MouvementRecurrent)
    end
  end

  describe "GET edit" do
    it "assigns the requested mouvement_recurrent as @mouvement_recurrent" do
      mouvement_recurrent = MouvementRecurrent.create! valid_attributes
      get :edit, {:id => mouvement_recurrent.to_param}, valid_session
      assigns(:mouvement_recurrent).should eq(mouvement_recurrent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MouvementRecurrent" do
        expect {
          post :create, {:mouvement_recurrent => valid_attributes}, valid_session
        }.to change(MouvementRecurrent, :count).by(1)
      end

      it "assigns a newly created mouvement_recurrent as @mouvement_recurrent" do
        post :create, {:mouvement_recurrent => valid_attributes}, valid_session
        assigns(:mouvement_recurrent).should be_a(MouvementRecurrent)
        assigns(:mouvement_recurrent).should be_persisted
      end

      it "redirects to the created mouvement_recurrent" do
        post :create, {:mouvement_recurrent => valid_attributes}, valid_session
        response.should redirect_to(MouvementRecurrent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mouvement_recurrent as @mouvement_recurrent" do
        # Trigger the behavior that occurs when invalid params are submitted
        MouvementRecurrent.any_instance.stub(:save).and_return(false)
        post :create, {:mouvement_recurrent => {}}, valid_session
        assigns(:mouvement_recurrent).should be_a_new(MouvementRecurrent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MouvementRecurrent.any_instance.stub(:save).and_return(false)
        post :create, {:mouvement_recurrent => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mouvement_recurrent" do
        mouvement_recurrent = MouvementRecurrent.create! valid_attributes
        # Assuming there are no other mouvement_recurrents in the database, this
        # specifies that the MouvementRecurrent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MouvementRecurrent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mouvement_recurrent.to_param, :mouvement_recurrent => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mouvement_recurrent as @mouvement_recurrent" do
        mouvement_recurrent = MouvementRecurrent.create! valid_attributes
        put :update, {:id => mouvement_recurrent.to_param, :mouvement_recurrent => valid_attributes}, valid_session
        assigns(:mouvement_recurrent).should eq(mouvement_recurrent)
      end

      it "redirects to the mouvement_recurrent" do
        mouvement_recurrent = MouvementRecurrent.create! valid_attributes
        put :update, {:id => mouvement_recurrent.to_param, :mouvement_recurrent => valid_attributes}, valid_session
        response.should redirect_to(mouvement_recurrent)
      end
    end

    describe "with invalid params" do
      it "assigns the mouvement_recurrent as @mouvement_recurrent" do
        mouvement_recurrent = MouvementRecurrent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MouvementRecurrent.any_instance.stub(:save).and_return(false)
        put :update, {:id => mouvement_recurrent.to_param, :mouvement_recurrent => {}}, valid_session
        assigns(:mouvement_recurrent).should eq(mouvement_recurrent)
      end

      it "re-renders the 'edit' template" do
        mouvement_recurrent = MouvementRecurrent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MouvementRecurrent.any_instance.stub(:save).and_return(false)
        put :update, {:id => mouvement_recurrent.to_param, :mouvement_recurrent => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mouvement_recurrent" do
      mouvement_recurrent = MouvementRecurrent.create! valid_attributes
      expect {
        delete :destroy, {:id => mouvement_recurrent.to_param}, valid_session
      }.to change(MouvementRecurrent, :count).by(-1)
    end

    it "redirects to the mouvement_recurrents list" do
      mouvement_recurrent = MouvementRecurrent.create! valid_attributes
      delete :destroy, {:id => mouvement_recurrent.to_param}, valid_session
      response.should redirect_to(mouvement_recurrents_url)
    end
  end

end
